### ISSUE TITLE
TestPhenixRSRefine fails

### ISSUE THREAD

**Issue by yaizar** [scipion-em/scipion-em-phenix#1]
```
[   FAILED ] TestPhenixRSRefine.testPhenixRSRefineFromVolumeAndCIF9
Traceback (most recent call last):
  File "/home/buildbot/scipionBot/devel/scipion/software/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/buildbot/scipionBot/devel/scipion/software/lib/python2.7/site-packages/phenix/tests/test_protocol_real_space_refine.py", line 647, in testPhenixRSRefineFromVolumeAndCIF9
    protRSRefine=protRSRefine)
  File "/home/buildbot/scipionBot/devel/scipion/software/lib/python2.7/site-packages/phenix/tests/test_protocol_real_space_refine.py", line 191, in checkRSRefineResults
    ramFavored, places)
  File "/home/buildbot/scipionBot/devel/scipion/software/lib/python2.7/unittest/case.py", line 555, in assertAlmostEqual
    if round(abs(second-first), places) == 0:
TypeError: unsupported operand type(s) for -: 'float' and 'Float'
```

**Comment by rmarabini** [comment]
buildbot is working now
