### ISSUE TITLE
phenix -> analyze any plot fails in diriletch

### ISSUE THREAD

**Issue by rmarabini** [scipion-em/scipion-em-phenix#3]
Show any plot from analyze fails in diriletch but script run from command line works:

cd /home/gabriela/ScipionUserData/projects/TsV-N1-refinamiento
/usr/local/phenix-1.13/build/bin/phenix.python  Runs/000487_PhenixProtRunRSRefine/tmp/Multi_criterion_plot.py

ERROR:
** Running command: phenix.python  Runs/000487_PhenixProtRunRSRefine/tmp/tmpAnalysisFile.py
** Running command: phenix.python  Runs/000487_PhenixProtRunRSRefine/tmp/Multi_criterion_plot.py
X11 connection rejected because of wrong authentication.
Unable to access the X Display, is $DISPLAY set properly?
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/local/scipion/software/lib/python2.7/lib-tk/Tkinter.py", line 1541, in __call__
    return self.func(*args)
  File "/usr/local/scipion/pyworkflow/gui/form.py", line 1207, in _visualizeVar
    self.visualizeCallback(self.paramName)
  File "/usr/local/scipion/pyworkflow/viewer.py", line 309, in _visualizeParam
    print("_visualizeParam", self._getVisualizeDict()[paramName](paramName))
  File "/usr/local/Plugins/scipion-em-phenix/phenix/viewers/viewer_refinement_base.py", line 848, in _showMultiCriterionPlot
    Plugin.runPhenixProgram("", self.TMPFILENAME)
  File "/usr/local/Plugins/scipion-em-phenix/phenix/__init__.py", line 78, in runPhenixProgram
    pwutils.runJob(None, program, args, env=env, cwd=cwd)
  File "/usr/local/scipion/pyworkflow/utils/process.py", line 52, in runJob
    return runCommand(command, env, cwd)
  File "/usr/local/scipion/pyworkflow/utils/process.py", line 67, in runCommand
    env=env, cwd=cwd)
  File "/usr/local/scipion/software/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'phenix.python  Runs/000487_PhenixProtRunRSRefine/tmp/Multi_criterion_plot.py' returned non-zero exit status 1

**Comment by mmmtnez** [comment]
I think this is fixed also
