### ISSUE TITLE
DISPLAY lost when using phenix.python in analize

### ISSUE THREAD

**Issue by mmmtnez** [scipion-em/scipion-em-phenix#5]
connect using ssh -X user@machine
execute molprobity
press analyze
try to visualize ramachandran plot. We get the error:

X11 connection rejected because of wrong authentication.
Unable to access the X Display, is $DISPLAY set properly?
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/marta/software/scipion_plugin/software/lib/python2.7/lib-tk/Tkinter.py", line 1541, in __call__
    return self.func(*args)
  File "/home/marta/software/scipion_plugin/pyworkflow/gui/form.py", line 1207, in _visualizeVar
    self.visualizeCallback(self.paramName)
  File "/home/marta/software/scipion_plugin/pyworkflow/viewer.py", line 314, in _visualizeParam
    views = self._getVisualizeDict()[paramName](paramName)
  File "/home/marta/software/scipion-em-phenix/phenix/viewers/viewer_refinement_base.py", line 818, in _showPlotType
    Plugin.runPhenixProgram("", self.TMPFILENAME)
  File "/home/marta/software/scipion-em-phenix/phenix/__init__.py", line 86, in runPhenixProgram
    pwutils.runJob(None, program, args, env=env, cwd=cwd)
  File "/home/marta/software/scipion_plugin/pyworkflow/utils/process.py", line 52, in runJob
    return runCommand(command, env, cwd)
  File "/home/marta/software/scipion_plugin/pyworkflow/utils/process.py", line 67, in runCommand
    env=env, cwd=cwd)
  File "/home/marta/software/scipion_plugin/software/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'phenix.python  Runs/001064_PhenixProtRunMolprobity/tmp/Ramachandran_write_plot.py' returned non-zero exit status 1
-------------------------------
It seems that DISPLAY is not setup properlly when we call phenix.python

**Comment by mmmtnez** [comment]
fixed, HOME enviromental variable was missing
